export const mydefault = [
    [
        {
            name: [""],
            dia: "lunes",
            hora: "mañana",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "martes",
            hora: "mañana",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "miercoles",
            hora: "mañana",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "jueves",
            hora: "mañana",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "viernes",
            hora: "mañana",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "sabado",
            hora: "mañana",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "domingo",
            hora: "mañana",
            puesto: "tienda",
        },
    ],
    [
        {
            name: [""],
            dia: "lunes",
            hora: "mañana",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "martes",
            hora: "mañana",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "miercoles",
            hora: "mañana",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "jueves",
            hora: "mañana",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "viernes",
            hora: "mañana",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "sabado",
            hora: "mañana",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "domingo",
            hora: "mañana",
            puesto: "pista",
        },
    ],
    [
        {
            name: [""],
            dia: "lunes",
            hora: "tarde",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "martes",
            hora: "tarde",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "miercoles",
            hora: "tarde",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "jueves",
            hora: "tarde",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "viernes",
            hora: "tarde",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "sabado",
            hora: "tarde",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "domingo",
            hora: "tarde",
            puesto: "tienda",
        },
    ],
    [
        {
            name: [""],
            dia: "lunes",
            hora: "tarde",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "martes",
            hora: "tarde",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "miercoles",
            hora: "tarde",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "jueves",
            hora: "tarde",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "viernes",
            hora: "tarde",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "sabado",
            hora: "tarde",
            puesto: "pista",
        },
        {
            name: [""],
            dia: "domingo",
            hora: "tarde",
            puesto: "pista",
        },
    ],
    [
        {
            name: [""],
            dia: "lunes",
            hora: "noche",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "martes",
            hora: "noche",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "miercoles",
            hora: "noche",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "jueves",
            hora: "noche",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "viernes",
            hora: "noche",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "sabado",
            hora: "noche",
            puesto: "tienda",
        },
        {
            name: [""],
            dia: "domingo",
            hora: "noche",
            puesto: "tienda",
        },
    ],
    [
        {
            name: [""],
            dia: "lunes",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "martes",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "miercoles",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "jueves",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "viernes",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "sabado",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "domingo",
            hora: "libre",
            puesto: "",
        },
    ],
    [
        {
            name: [""],
            dia: "lunes",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "martes",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "miercoles",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "jueves",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "viernes",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "sabado",
            hora: "libre",
            puesto: "",
        },
        {
            name: [""],
            dia: "domingo",
            hora: "libre",
            puesto: "",
        },
    ],
];
