export const trabajadores = [
    {
        name: "Richar",
        tienda: 5,
        pista: 0,
        manana: 0,
        tarde: 0,
        noche: 5,
        renganche: 2,
        libre: [0, 1],
        jornadas: 5,
        yajornada: false,
        historico: [{ fecha: 6545648456, semana: [4, 5, 5, 4, 4, 4, 4] }],
        last: 4,
    },
    {
        name: "Lolo",
        tienda: 0,
        pista: 5,
        manana: 3,
        tarde: 2,
        noche: 0,
        renganche: 2,
        libre: [0, 6],
        jornadas: 5,
        yajornada: false,
        historico: [{ fecha: 6545648456, semana: [3, 5, 1, 1, 5, 1, 1] }],
        last: 1,
    },
    {
        name: "Rafa",
        tienda: 5,
        pista: 0,
        manana: 2,
        tarde: 3,
        noche: 2,
        renganche: 2,
        libre: [1, 2],
        jornadas: 5,
        yajornada: false,
        historico: [{ fecha: 6545648456, semana: [5, 4, 4, 5, 2, 2, 2] }],
        last: 2,
    },
    {
        name: "Judith",
        tienda: 5,
        pista: 0,
        manana: 5,
        tarde: 0,
        noche: 0,
        renganche: 0,
        libre: [2, 3],
        jornadas: 5,
        yajornada: false,
        historico: [{ fecha: 6545648456, semana: [0, 0, 0, 0, 0, 5, 5] }],
        last: 5,
    },
    {
        name: "Edward",
        tienda: 1,
        pista: 4,
        manana: 3,
        tarde: 2,
        noche: 0,
        renganche: 2,
        libre: [3, 4],
        jornadas: 5,
        yajornada: false,
        historico: [{ fecha: 6545648456, semana: [1, 1, 2, 5, 1, 5, 0] }],
        last: 0,
    },
    {
        name: "Victor",
        tienda: 4,
        pista: 1,
        manana: 3,
        tarde: 2,
        noche: 0,
        renganche: 2,
        libre: [4, 5],
        jornadas: 5,
        yajornada: false,
        historico: [{ fecha: 6545648456, semana: [5, 2, 5, 2, 3, 0, 3] }],
        last: 3,
    },
    {
        name: "Nuñes",
        tienda: 0,
        pista: 5,
        manana: 1,
        tarde: 4,
        noche: 0,
        renganche: 2,
        libre: [5, 6],
        jornadas: 5,
        yajornada: false,
        historico: [{ fecha: 6545648456, semana: [2, 3, 3, 3, 5, 3, 5] }],
        last: 5,
    },
];
