export const trabajadores = [
    {
        name: "Richar",
        tienda: 5,
        pista: 0,
        manana: 0,
        tarde: 0,
        noche: 5,
        renganche: 2,
        libre: [2, 1],
        yajornada: false,
        fuetarde: false,
        fuenoche: false,
        semana: {
            fecha: "",
            horario: [
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
            ],
        },
    },
    {
        name: "Lolo",
        tienda: 0,
        pista: 5,
        manana: 3,
        tarde: 2,
        noche: 0,
        renganche: 2,
        libre: [1, 4],
        yajornada: false,
        fuetarde: false,
        fuenoche: false,
        semana: {
            fecha: "",
            horario: [
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
            ],
        },
    },
    {
        name: "Rafa",
        tienda: 5,
        pista: 0,
        manana: 2,
        tarde: 3,
        noche: 2,
        renganche: 2,
        libre: [3, 0],
        yajornada: false,
        fuetarde: false,
        fuenoche: false,
        semana: {
            fecha: "",
            horario: [
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
            ],
        },
    },
    {
        name: "Judith",
        tienda: 5,
        pista: 0,
        manana: 5,
        tarde: 0,
        noche: 0,
        renganche: 0,
        libre: [5, 6],
        yajornada: false,
        fuetarde: false,
        fuenoche: false,
        semana: {
            fecha: "",
            horario: [
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
            ],
        },
    },
    {
        name: "Edward",
        tienda: 2,
        pista: 3,
        manana: 3,
        tarde: 2,
        noche: 0,
        renganche: 2,
        libre: [4, 5],
        yajornada: false,
        fuetarde: false,
        fuenoche: false,
        semana: {
            fecha: "",
            horario: [
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
            ],
        },
    },
    {
        name: "Victor",
        tienda: 4,
        pista: 1,
        manana: 3,
        tarde: 2,
        noche: 0,
        renganche: 2,
        libre: [0, 2],
        yajornada: false,
        fuetarde: false,
        fuenoche: false,
        semana: {
            fecha: "",
            horario: [
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
            ],
        },
    },
    {
        name: "Nuñes",
        tienda: 0,
        pista: 4,
        manana: 1,
        tarde: 4,
        noche: 0,
        renganche: 2,
        libre: [3, 6],
        yajornada: false,
        fuetarde: false,
        fuenoche: false,
        semana: {
            fecha: "",
            horario: [
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
                { valor: null, forced: false },
            ],
        },
    },
];
