export const store = {
    conf: {
        index: 0,
        checked: false,
        desabled: true,
        alert: false,
    },
    trabajadores: [
        {
            name: "Lolo",
            tienda: 0,
            pista: 5,
            manana: 3,
            tarde: 2,
            noche: 0,
            yajornada: false,
            fuetarde: false,
            fuenoche: false,
            fuelibre: false,
            semana: {
                fecha: "",
                horario: [
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                ],
            },
        },
        {
            name: "Rafa",
            tienda: 5,
            pista: 0,
            manana: 2,
            tarde: 3,
            noche: 2,
            yajornada: false,
            fuetarde: false,
            fuenoche: false,
            fuelibre: false,
            semana: {
                fecha: "",
                horario: [
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                ],
            },
        },
        {
            name: "Edward",
            tienda: 2,
            pista: 3,
            manana: 3,
            tarde: 2,
            noche: 0,
            yajornada: false,
            fuetarde: false,
            fuenoche: false,
            fuelibre: false,
            semana: {
                fecha: "",
                horario: [
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                ],
            },
        },
        {
            name: "Victor",
            tienda: 4,
            pista: 1,
            manana: 3,
            tarde: 2,
            noche: 0,
            yajornada: false,
            fuetarde: false,
            fuenoche: false,
            fuelibre: false,
            semana: {
                fecha: "",
                horario: [
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                ],
            },
        },
        {
            name: "Jaime",
            tienda: 2,
            pista: 3,
            manana: 2,
            tarde: 3,
            noche: 0,
            yajornada: false,
            fuetarde: false,
            fuenoche: false,
            fuelibre: false,
            semana: {
                fecha: "",
                horario: [
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                ],
            },
        },

        {
            name: "Richar",
            tienda: 5,
            pista: 0,
            manana: 0,
            tarde: 0,
            noche: 5,
            yajornada: false,
            fuetarde: false,
            fuenoche: false,
            fuelibre: false,
            semana: {
                fecha: "",
                horario: [
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                ],
            },
        },
        {
            name: "Nuñes",
            tienda: 1,
            pista: 4,
            manana: 1,
            tarde: 4,
            noche: 0,
            yajornada: false,
            fuetarde: false,
            fuenoche: false,
            fuelibre: false,
            semana: {
                fecha: "",
                horario: [
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                    { valor: null, forced: false },
                ],
            },
        },
    ],
    semanaDefault: [
        [
            {
                name: ["Lolo"],
                dia: "lunes",
                hora: "mañana",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "martes",
                hora: "mañana",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "miercoles",
                hora: "mañana",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "jueves",
                hora: "mañana",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "viernes",
                hora: "mañana",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "sabado",
                hora: "mañana",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "domingo",
                hora: "mañana",
                puesto: "tienda",
            },
        ],
        [
            {
                name: [""],
                dia: "lunes",
                hora: "mañana",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "martes",
                hora: "mañana",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "miercoles",
                hora: "mañana",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "jueves",
                hora: "mañana",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "viernes",
                hora: "mañana",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "sabado",
                hora: "mañana",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "domingo",
                hora: "mañana",
                puesto: "pista",
            },
        ],
        [
            {
                name: [""],
                dia: "lunes",
                hora: "tarde",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "martes",
                hora: "tarde",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "miercoles",
                hora: "tarde",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "jueves",
                hora: "tarde",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "viernes",
                hora: "tarde",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "sabado",
                hora: "tarde",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "domingo",
                hora: "tarde",
                puesto: "tienda",
            },
        ],
        [
            {
                name: [""],
                dia: "lunes",
                hora: "tarde",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "martes",
                hora: "tarde",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "miercoles",
                hora: "tarde",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "jueves",
                hora: "tarde",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "viernes",
                hora: "tarde",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "sabado",
                hora: "tarde",
                puesto: "pista",
            },
            {
                name: [""],
                dia: "domingo",
                hora: "tarde",
                puesto: "pista",
            },
        ],
        [
            {
                name: [""],
                dia: "lunes",
                hora: "noche",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "martes",
                hora: "noche",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "miercoles",
                hora: "noche",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "jueves",
                hora: "noche",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "viernes",
                hora: "noche",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "sabado",
                hora: "noche",
                puesto: "tienda",
            },
            {
                name: [""],
                dia: "domingo",
                hora: "noche",
                puesto: "tienda",
            },
        ],
        [
            {
                name: [""],
                dia: "lunes",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "martes",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "miercoles",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "jueves",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "viernes",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "sabado",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "domingo",
                hora: "libre",
                puesto: "",
            },
        ],
        [
            {
                name: [""],
                dia: "lunes",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "martes",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "miercoles",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "jueves",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "viernes",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "sabado",
                hora: "libre",
                puesto: "",
            },
            {
                name: [""],
                dia: "domingo",
                hora: "libre",
                puesto: "",
            },
        ],
    ],
};
