export const types = {
    generaHorario: "Genera Horario",
    setIndex: "establecer index",
    toggleCheck: "Mostrar oculatar parametros",
    checkedTrue: "poner el checked en true",
    setManual: "Posiciones manuales del horario",
    setTienda: "parametro tienda",
    setPista: "parametro Pista",
    setManana: "parametro mañana",
    setTarde: "parametro  tarde",
    setNoche: "parametro Noche",
    setDomingo: "Lo que hizo el domingo",
    setName: "Nombre del trabajador",
    reset: "reiniciar todo",
};
